on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: | #upgrade the actions container to 24.04 because 22.04 doesn't have some of the deps
          sudo sed -i 's/jammy/noble/' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y sbuild-qemu quilt build-essential fakeroot devscripts dh-make dh-nss dpkg-dev dh-package-notes

      - name: Build
        run:
          sudo ./build_repo.sh
          mv repo/ website/debian/

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b8079ffa92c97010f2a8d759e24cc782
          projectName: shimboot
          directory: website